# develop stage
FROM node:22-alpine AS develop-stage
WORKDIR /web
COPY ./package.json /web/package.json
COPY ./yarn.lock /web/yarn.lock
COPY ./tsconfig.json ./vite.config.ts /web/
COPY ./index.html /web/index.html
RUN yarn install --frozen-lockfile || yarn install
COPY ./src /web/src

# build stage
FROM develop-stage AS build-stage
RUN yarn build


# production stage
FROM nginx:alpine AS production-stage
COPY --from=build-stage /web/dist /usr/share/nginx/html
EXPOSE 80
