name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: cd ./frontend && yarn install --frozen-lockfile
      - name: Run prettier on frontend
        run: cd ./frontend && yarn run format:check
      - name: Run eslint on frontend
        run: cd ./frontend && yarn run lint
